### ISSUE TITLE
Suggestion for dependabot

### ISSUE THREAD

**Issue by ccoVeille** [Zxilly/go-size-analyzer#119]
May I suggest you to use the `groups` feature in dependabot?

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups

This could reduce the number of PRs

**Comment by Zxilly** [comment]
I know this, but I'm not sure which dependencies I should put into groups.
In kotlin, sometimes different dependencies share the same version number, and when upgrading, you need to upgrade all of them, so you need to group them, but this is the rare case in js.

**Comment by ccoVeille** [comment]
Mt ideas is a o group the PR, so to reduce the noise of dependabot.
