### ISSUE TITLE
About alternative

### ISSUE THREAD

**Issue by ccoVeille** [Zxilly/go-size-analyzer#13]
Hi @Zxilly 

I saw your starred @bradfitz https://github.com/bradfitz/shotizam

Can you explain how they differ and how they are close, except the rendering format. I'm more interested in the way to analyze things.

Was shotizam a part of your inspirations, or you just found it out?

Were there other projects that existed before and that inspired you ?

Would you consider to add a mention about alternatives to your Readme file.

Thanks, Christophe

**Comment by Zxilly** [comment]
I just found it out and not read the details.  This project was inspired by a blog of cockroachlab https://www.cockroachlabs.com/blog/go-file-size/

**Comment by ccoVeille** [comment]
Thanks for your reply, I think you could talk about why you created the project and about the blog posts in your Readme

I find very interesting to read about such a thing on project page.

**Comment by ccoVeille** [comment]
So did this project mentioned on the blog was a source of inspiration to you ?

https://github.com/knz/go-binsize-viz/forks

**Comment by Zxilly** [comment]
Yes, but it relies on some linux tools and I develop mostly in Windows and are complicated to use. So I decided to write one myself.
I don't like to mention things in the README that the user might not want to care about, maybe later I'll write a blog explaining exactly how this tool works, and at that time I can add some little stories.

**Comment by ccoVeille** [comment]
at least this issue exists for reference

thanks, you can close
