### ISSUE TITLE
1.5.2 release build failure

### ISSUE THREAD

**Issue by chenrui333** [Zxilly/go-size-analyzer#151]
seeing some release build failure in https://github.com/Homebrew/homebrew-core/pull/177777

```
# github.com/Zxilly/go-size-analyzer/internal
internal/analyze.go:47:20: k.UpdateVersionFlag undefined (type *knowninfo.KnownInfo has no field or method UpdateVersionFlag)
```

also, might not be a good idea to use rc release for release binary shipping?

**Comment by Zxilly** [comment]
Will be fixed in v1.5.3. 

The rc version is used because this program can be very memory hungry and therefore highly dependent on the 1.23 unique library.

**Comment by Zxilly** [comment]
Fixed in https://github.com/Zxilly/go-size-analyzer/releases/tag/v1.5.3

**Comment by chenrui333** [comment]
Thanks @Zxilly!
