### ISSUE TITLE
Analysing CGO libraries

### ISSUE THREAD

**Issue by ayuhito** [Zxilly/go-size-analyzer#19]
Not sure if this is possible, but maybe it would be a useful feature to be able to analyze CGO libraries and their footprint? e.g. I'm using https://github.com/mattn/go-sqlite3 and https://github.com/marcboeker/go-duckdb which leads to a very large obscure 30MB `.text` section that doesn't really tell me much. 

Thank you for this project! It's helped me a lot!

**Comment by Zxilly** [comment]
It's possible after the dwarf analysis be implemented. Currently any cgo dependencies will be ignored.

**Comment by Zxilly** [comment]
Please try v1.2.0, it should have a basic cgo dependency support. Only works if the binary contains dwarf debugging information.
