### ISSUE TITLE
move DWARF sections out of unknown sections

### ISSUE THREAD

**Issue by gudvinr** [Zxilly/go-size-analyzer#196]
**Is your feature request related to a problem? Please describe.**

Right now "Unknown sections" are populated by significant amount of DWARF sections, like `.debug_info`, `.debug_loc`, etc.  
Strictly speaking, these sections are known and and can be stripped with `-ldflags '-s -w'`.

**Describe the solution you'd like**

These sections could be split into separate category.  
I don't know if it makes sense to parse sections to display more detailed information because it is likely not actionable.

Here's the difference between stripped and unstripped binaries:

![unstripped](https://github.com/user-attachments/assets/47a5c5b2-a038-494c-9448-76f78bf44dca)
![stripped](https://github.com/user-attachments/assets/cb110ae1-5362-4247-89f5-2a01f34daa85)

**Comment by Zxilly** [comment]
I had thought about adding an --assume-strip parameter, but then realized it was difficult to calculate the exact volume impact, so I shelved it. But just adding the markers looks doable.
