### ISSUE TITLE
not support grable obfuscated binary

### ISSUE THREAD

**Issue by lysShub** [Zxilly/go-size-analyzer#227]
**Describe the bug**
build use https://github.com/burrowers/garble

gsa --listen=":8080" --open b.exe
time=62.9101ms level=ERROR msg="Fatal error: error when getting pclntab: no pclntab located"

**Comment by Zxilly** [comment]
This project is based on reverse engineering, and apparently, when you use obfuscation, reversing becomes so difficult that it's almost impossible to automate.

**Comment by lysShub** [comment]
好吧
