### ISSUE TITLE
Could redress help/inspire you?

### ISSUE THREAD

**Issue by ccoVeille** [Zxilly/go-size-analyzer#26]
Hi @Zxilly 

I found this project and thought about you and your project

https://github.com/goretk/redress

So I'm sharing. You are the one who may know if it could have a need.

Regards

**Comment by Zxilly** [comment]
redress and this project both rely on [gore](https://github.com/goretk/gore). Before starting this project, I was involved in maintaining gore to make sure it met the needs of this project. Anyway, thanks for reminding me.

**Comment by ccoVeille** [comment]
Thanks. I know understand why you rocks so much with this project. You "had a lot fun" with previous ones
