### ISSUE TITLE
无法使用 disasm.go checkX86代码报错

### ISSUE THREAD

**Issue by wzhsh90** [Zxilly/go-size-analyzer#3]
1、在ubuntu 下根本无法使用
2、文档里面的参数在程序里面没有

**Comment by Zxilly** [comment]
现在这个Golang版本还在重构，没有写完，可以从release下编译好的或者checkout rust分支自己编译

**Comment by wzhsh90** [comment]
好的，马上来用



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月16日(周二) 下午3:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Zxilly/go-size-view] 无法使用 disasm.go checkX86代码报错 (Issue #3)




 
现在这个Golang版本还在重构，没有写完，可以从release下编译好的或者checkout rust分支自己编译
