### ISSUE TITLE
Add CI via GitHub actions

### ISSUE THREAD

**Issue by ccoVeille** [Zxilly/go-size-analyzer#32]
I'm thinking about adding something that will launch go test and golangci-lint to validate no regression are added and code quality is preserved

**Comment by ccoVeille** [comment]
I can add these, of course

**Comment by Zxilly** [comment]
There are already some scripts for testing, you can check the [scripts/tests.py](https://github.com/Zxilly/go-size-analyzer/blob/e1be139c8ffac238b715be446324480ed6806672/scripts/tests.py)

**Comment by ccoVeille** [comment]
Oh indeed, thanks for pointing me them so it would be only about adding such CI actions like `typos` and `golangci-lint`

[typos](https://github.com/crate-ci/typos) might be added via https://github.com/marketplace/actions/typos-action I would say a GHA is better for this than something added to `tests.py`

about golangci-lint, I would say the same, as it would allow the action to report the error inline on PR annotations

https://github.com/golangci/golangci-lint-action

**Comment by ccoVeille** [comment]
Here is what I get with golangci reporting locally

```
181 issues:
* errorlint: 1
* gci: 81
* gosec: 3
* gosimple: 2
* govet: 1
* ineffassign: 2
* misspell: 1
* noctx: 2
* revive: 77
* staticcheck: 2
* testifylint: 7
* unused: 1
* usestdlibvars: 1
```

I think your project needs it :grin:

**Comment by ccoVeille** [comment]
Good. It seems it starts to help you.

I like how linters help to write cleaner code.

I don't think I would have thought about generics to fix the type issues 👍
