### ISSUE TITLE
Support for installation using homebrew

### ISSUE THREAD

**Issue by kishaningithub** [Zxilly/go-size-analyzer#37]
It would be great if i an just perform `brew install` to install go-size-analyzer in my system.

I see this project uses goreleaser and it supports generation of homebrew formulas

https://goreleaser.com/customization/homebrew/?h=homebrew#versioned-formulas

Since homebrew supports both mac and linux, users of both platforms can benefit from this

**Comment by ccoVeille** [comment]
I'm on Linux and I love using homebrew to install my Go Dev tools and make sure they are always up to date.

It's pretty easy ( _famous last words_™️) to set up, with an home "tap" via go releaser.

**Comment by Zxilly** [comment]
I have created a PR for homebrew https://github.com/Homebrew/homebrew-core/pull/171603 , let's wait for the feedback from maintainer.

**Comment by ccoVeille** [comment]
Great addition thanks

You will be able to follow the number of installation from this page

https://formulae.brew.sh/formula/go-size-analyzer#default

There is also an API, or you can get information via brew CLI
