### ISSUE TITLE
Report is missing elements

### ISSUE THREAD

**Issue by kishaningithub** [Zxilly/go-size-analyzer#38]
I ran this for my tool [tf-import-gen](https://github.com/kishaningithub/tf-import-gen). The unstripped binary size is ~6.2 MB and i wanted to look into what was causing it.

## What i did
- Went into the folder where i have checkout my [tf-import-gen repo](https://github.com/kishaningithub/tf-import-gen)
- Ran command `CGO_ENABLED=0 go build`
- Ran command `gsa --web ./tf-import-gen` 
- Opened the web report

## What i saw

If you see in the below screenshot the "Package Size" is 2.81 MB but the largest bar within that "Vendor packages size" ~591 KB hence i am not sure where the mega bytes are going

Screenshot 1
<img width="800" alt="image" src="https://github.com/Zxilly/go-size-analyzer/assets/763760/c1c95d8e-875b-41bd-9987-26a5880fa290">

Screenshot 2
<img width="800" alt="image" src="https://github.com/Zxilly/go-size-analyzer/assets/763760/138afb13-cd92-4d34-8d21-ad76cb842304">

**Comment by Zxilly** [comment]
I test it on Linux and seems vendor packages cost 683 kb and standard library packages cost 2.

**Comment by Zxilly** [comment]
Maybe the rendered colours are a bit misleading, I would add different colours for different package types

**Comment by kishaningithub** [comment]
I thought the unknown sections size on the right hand side (coloured in light red) which is also like 2 MB was the standard lib. Is it not?

**Comment by Zxilly** [comment]
Generally, unknown is meta information in the binary format itself, such as elf's section header and program header. but it's generally not that big, so if you can provide a sample of the binary file, I can do further analysis.

**Comment by kishaningithub** [comment]
@Zxilly Putting below all the information i can get including the binary file. Can you kindly re open this issue?

## Zipped binary
[tf-import-gen.zip](https://github.com/Zxilly/go-size-analyzer/files/15344625/tf-import-gen.zip)

## Size Screenshot
<img width="1633" alt="image" src="https://github.com/Zxilly/go-size-analyzer/assets/763760/144b7f9d-352a-433c-84b6-8ee430616437">

## gsa version

```bash
$ gsa --version
gsa
  Version          v1.0.6
  Go Version       go1.22.3
  Platform         darwin/arm64
```

## Screenshot of startup Warning message

level=WARN msg="Warning: disassembler not supported for this architecture"
<img width="705" alt="image" src="https://github.com/Zxilly/go-size-analyzer/assets/763760/c5b12256-2a3d-4eca-b794-c41747100deb">

**Comment by Zxilly** [comment]
It does look like there are some issues with macos support, but I think I'd have a hard time fixing it, I work on amd64 on Windows/Linux and support for other architectures and systems is basically based on documentation rather than real experience.

![image](https://github.com/Zxilly/go-size-analyzer/assets/31370133/d09f117a-18a8-4825-9117-9c7afc4c07ff)

I test the binary from the https://github.com/kishaningithub/tf-import-gen/releases/download/v0.8.0/tf-import-gen_0.8.0_linux_amd64.tar.gz and results looks better.

As you can see from the figure, the binary size can be reduced by about 6m after stripping the symbol and debug information.

**Comment by kishaningithub** [comment]
Will check the Linux version today.. Was curious to see how much size can be reduced without removing the debug and symbol table info

**Comment by kishaningithub** [comment]
Also I can definitely help out on testing and improving this tool for Mac os

**Comment by kishaningithub** [comment]
After removing the symbol table and debug information the compressed size went from ~3MB to ~1MB :-) screenshot and link below

https://github.com/kishaningithub/tf-import-gen/releases

## Screenshot
<img width="900" alt="image" src="https://github.com/Zxilly/go-size-analyzer/assets/763760/e5e37f86-8006-42ac-81bf-e42228dca1b9">

**Comment by kishaningithub** [comment]
After the removal of debug information the size reported looks correct in macos x (screenshot below)

<img width="1606" alt="image" src="https://github.com/Zxilly/go-size-analyzer/assets/763760/b6fa6dc2-f8f7-428b-a9a7-dd66319aa6e2">

Closing this issue for now
