### ISSUE TITLE
how to install gsv

### ISSUE THREAD

**Issue by 1111chengtong** [Zxilly/go-size-analyzer#4]
Could you explain how to install gsv in README

**Comment by Zxilly** [comment]
The current code base is under refactoring and is not available. You can download the legacy version from the release. It only works on linux.

**Comment by Zxilly** [comment]
Now you can download `gsa` from release. Looking forward to your reply!

**Comment by Zxilly** [comment]
Didn't notice any recent activity, so I'm closing this issue. feel free to reopen if there are any more questions!
