### ISSUE TITLE
an app compiled against "tailscale.com/tsnet" panics with "...type text and data conflict"

### ISSUE THREAD

**Issue by marcellmars** [Zxilly/go-size-analyzer#5]
compiling [tsnet-funnel](https://raw.githubusercontent.com/tailscale/tailscale/main/tsnet/example/tsnet-funnel/tsnet-funnel.go) should work as advertised.

`gsa` ends up with `panic: addr xxxx type text and data conflict`

**Comment by Zxilly** [comment]
Can you provide your compile command?  I will investigate

**Comment by Zxilly** [comment]
try https://github.com/Zxilly/go-size-analyzer/releases/tag/0.2.1

**Comment by marcellmars** [comment]
> try https://github.com/Zxilly/go-size-analyzer/releases/tag/0.2.1

works!

for me minor annoyance as i don't use it but `--web` doesn't work for me with any combination with `--open` and/or `--listen=:xxxx`... will close this one and maybe open another issue if i will need it...

thank you for this tool and quick resolve...

**Comment by Zxilly** [comment]
the bug on the `--web` flag has been fixed in 0.2.2
