### ISSUE TITLE
Anyway to reduce the memory use?

### ISSUE THREAD

**Issue by joway** [Zxilly/go-size-analyzer#6]
For some binary with large size(like 400MB), it will OOM killed by os. My host have 180GB Memory....

**Comment by Zxilly** [comment]
I think there are many tools focused on this, or just use builtin pprof.
Mostly the running memory usage are not related to the binary size.

**Comment by Zxilly** [comment]
Oh, I understand what you means now.
Are there any samples you can provide? I'm analysing about 200 megabytes of k8s binary and it's working fine.

**Comment by Zxilly** [comment]
One reason I can imagine is that the decompile creates too many go routine in a split second, consuming all the available memory, but I don't think it's likely to squeeze a machine with 180g of RAM.
I'll try to put a limit on it and please let me know if this fixes your problem.

**Comment by Zxilly** [comment]
A configurable gc parameter was added in 1.0.5
