### ISSUE TITLE
go-size-analyzer 1.3.0 regression test failure

### ISSUE THREAD

**Issue by chenrui333** [Zxilly/go-size-analyzer#83]
👋 trying to build the latest release, but run into some test issue. The error log is as below:

<details>
<summary>error test log</summary>

```
$ gsa --verbose hello
time=1.397833ms level=INFO msg="Parsing binary..."
time=5.678167ms level=INFO msg="Parsing binary done"
time=5.700458ms level=INFO msg="Finding build info..."
time=5.875ms level=INFO msg="Build info found"
time=6.034333ms level=INFO msg="Loading sections..."
time=6.056958ms level=INFO msg="Loading sections done"
time=6.222208ms level=INFO msg="Loading packages..."
time=17.832042ms level=INFO msg="Loading packages done"
time=40.554917ms level=WARN msg="Failed to load DWARF var dwarf.Field{Attr:dwarf.AttrName, Val:\"runtime.startupRand\", Class:dwarf.ClassString}dwarf.Field{Attr:dwarf.AttrLocation, Val:[]uint8{0x3, 0x50, 0x1a, 0x14, 0x0, 0x1, 0x0, 0x0, 0x0}, Class:dwarf.ClassExprLoc}dwarf.Field{Attr:dwarf.AttrType, Val:0x7b3b7, Class:dwarf.ClassReference}dwarf.Field{Attr:dwarf.AttrExternal, Val:true, Class:dwarf.ClassFlag}: byte slice len(2370821947417) != cap(71830128058207)"
time=43.298917ms level=ERROR msg="Fatal error: addr 100001000 pos Pos: Addr: 0 CodeSize: 696c626174695f5f Type: data\nAddrPos: Addr: 0 CodeSize: 696c626174695f5f Type: data Pkg: runtime Function:  SourceType: symbol and Pos: Addr: 100001000 CodeSize: 70 Type: text\nAddrPos: Addr: 100001000 CodeSize: 70 Type: text Pkg:  Function: go:buildid SourceType: pclntab conflict"
```

</details>

relates to Homebrew/homebrew-core#174638

**Comment by Zxilly** [comment]
https://github.com/Zxilly/go-size-analyzer/actions/runs/9528514615/job/26266277783

I also observed this in the integration test, but after running it again this issue disappeared, I thought it was a hard to reproduce bug, now it seems not.
It seems that this issue is only triggered on macOS platform. I am writing a patch to fix this issue.

**Comment by chenrui333** [comment]
> https://github.com/Zxilly/go-size-analyzer/actions/runs/9528514615/job/26266277783

interesting that it only failed with 13, I am kicking off a rerun for regression test all platforms. https://github.com/Homebrew/homebrew-core/actions/runs/9529126389/job/26268615467

**Comment by Zxilly** [comment]
I think the bug is probably due to missing bss segment detection for macOS platforms, please check if v1.3.1 fixes this issue.

**Comment by chenrui333** [comment]
Yeah, 1.3.1 works for me
