### ISSUE TITLE
panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by Nyx2022** [Zxilly/go-size-analyzer#88]
我分析一个我自己写的exe时，提示一下错误：
![image](https://github.com/Zxilly/go-size-analyzer/assets/51039208/ef5b68b5-68c2-4d2f-a732-b24f27baa632)

烦请修复一下呢

**Comment by Zxilly** [comment]
能提供样本吗，没有样本不太好分析。

暂时可以使用 --no-dwarf 来跳过 dwarf pass。

**Comment by Zxilly** [comment]
看着像是在 msvc 下编译的 cgo？ 处理 ucrt 的时候似乎有点问题。

**Comment by Zxilly** [comment]
麻烦提供完整的日志，使用 --verbose flag

**Comment by Zxilly** [comment]
[v1.3.4](https://github.com/Zxilly/go-size-analyzer/releases/tag/v1.3.4)
